name: Verify

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "**/*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "**/*.md"

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.7.0

      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.11.4

      - run: make verify

      - run: make deps-vuln

      - run: make build REVISION=${{ github.sha }}
